[program:qanything_service]
command=bash /home/blackhole/project/QAnything/scripts/start_service.sh
directory=/home/blackhole/project/QAnything
autostart=true
autorestart=true
stderr_logfile=/home/blackhole/project/QAnything/logs/run/qanything_service.err.log
stdout_logfile=/home/blackhole/project/QAnything/logs/run/qanything_service.out.log

